# Generated by Django 6.0.5 on 2026-05-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0002_alter_reviewvote_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordReset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("token", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
