name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.14
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root

      - name: Run Tests
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_task

          REDIS_URL: redis://localhost:6379/1

          SECRET_KEY: "django-insecure-(2s1kb2m=@ck5r49r2cf=2mf%0reaqbpt9@2z8cys1w5ai$#4d"

          DEBUG: True

          EMAIL_BACKEND: django.core.mail.backends.console.EmailBackend
          EMAIL_HOST: localhost
          EMAIL_PORT: 25
          EMAIL_USE_TLS: False
          EMAIL_HOST_USER: ''
          EMAIL_HOST_PASSWORD: ''
          DEFAULT_FROM_EMAIL: webmaster@localhost

          TEST_USER1_USERNAME: user1
          TEST_USER1_EMAIL: user1@example.com
          TEST_USER1_PASSWORD: P3HWptGG097fLf6U7502kzaPDDbG2ZJi4Rj7pP97cAs=

          TEST_USER2_USERNAME: user2
          TEST_USER2_EMAIL: user2@example.com
          TEST_USER2_PASSWORD: l+A04hA+YuIIEcMU7Dihz9W7iBsNrU/AdZf4k0GHdzc=
        run: |
          poetry run pytest
